option(MIRAI_WITH_GIT           "Enable git routine"                1)
option(MIRAI_WITH_WARNINGS      "Show all warnings during compile"  1)
option(MIRAI_SHARED             "Build shared library"              1)
option(MIRAI_EXAMPLES           "Build examples"                    0)
option(MIRAI_TOOLS              "Build tools"                       0)